{% set name = "montepy" %}
{% set version = "1.0.0a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/montepy-{{ version }}.tar.gz
  sha256: 401483c26b0da0580555edc470f70e1373b597d63075c05078d8d39bde44bed3


build:
  entry_points:
    - change_to_ascii = montepy._scripts.change_to_ascii:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.18
    - sly >=0.4,<=0.5

test:
  imports:
    - montepy
  commands:
    - pip check
    - change_to_ascii --help
    - python -m montepy -c --help
  requires:
    - python {{ python_min }}
    - pip
    - pytest 
    - hypothesis

about:
  summary: A library for reading, editing, and writing MCNP input files
  dev_url: https://github.com/idaholab/MontePy
  home: https://www.montepy.org/
  license: MIT
  license_file:
    - LICENSE
    - NOTICE.txt

extra:
  recipe-maintainers:
    - MicahGale
